# Generated by Django 5.2.8 on 2025-11-25 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do cargo', max_length=100, unique=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, help_text='Salario base do cargo', max_digits=10, null=True)),
                ('cbo', models.CharField(blank=True, help_text='Codigo CBO (Classificacao Brasileira de Ocupacoes)', max_length=10, null=True)),
                ('descricao', models.TextField(blank=True, help_text='Descricao das atribuicoes do cargo', null=True)),
                ('nivel', models.CharField(blank=True, help_text='Nivel hierarquico (Junior, Pleno, Senior, etc.)', max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o cargo esta ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricula', models.CharField(help_text='Matricula unica do funcionario', max_length=20, unique=True)),
                ('departamento', models.CharField(blank=True, help_text='Departamento/Setor', max_length=100, null=True)),
                ('tipo_contrato', models.CharField(choices=[('clt', 'CLT'), ('pj', 'Pessoa Juridica'), ('estagiario', 'Estagiario'), ('temporario', 'Temporario'), ('terceirizado', 'Terceirizado'), ('aprendiz', 'Jovem Aprendiz')], default='clt', max_length=20)),
                ('data_admissao', models.DateField(help_text='Data de admissao')),
                ('data_demissao', models.DateField(blank=True, help_text='Data de demissao (se aplicavel)', null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, help_text='Salario base', max_digits=10, null=True)),
                ('carga_horaria_semanal', models.PositiveIntegerField(default=44, help_text='Carga horaria semanal em horas')),
                ('turno', models.CharField(choices=[('diurno', 'Diurno'), ('noturno', 'Noturno'), ('integral', 'Integral'), ('flexivel', 'Flexivel')], default='diurno', max_length=20)),
                ('horario_entrada', models.TimeField(blank=True, help_text='Horario padrao de entrada', null=True)),
                ('horario_saida', models.TimeField(blank=True, help_text='Horario padrao de saida', null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('afastado', 'Afastado'), ('ferias', 'Em Ferias'), ('licenca', 'Em Licenca'), ('demitido', 'Demitido'), ('aposentado', 'Aposentado')], default='ativo', max_length=20)),
                ('tem_dependente', models.BooleanField(default=False, help_text='Indica se o funcionario possui dependentes cadastrados')),
                ('tamanho_camisa', models.CharField(blank=True, help_text='Tamanho da camisa (PP, P, M, G, GG, XG, etc.)', max_length=10, null=True)),
                ('tamanho_calca', models.CharField(blank=True, help_text='Tamanho da calca (36, 38, 40, 42, etc.)', max_length=10, null=True)),
                ('tamanho_botina', models.CharField(blank=True, help_text='Tamanho da botina/calcado (38, 39, 40, 41, etc.)', max_length=10, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('conta', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_conta', models.CharField(blank=True, help_text='Corrente, Poupanca, etc.', max_length=20, null=True)),
                ('pix', models.CharField(blank=True, help_text='Chave PIX', max_length=100, null=True)),
                ('ctps_numero', models.CharField(blank=True, help_text='Numero da CTPS', max_length=20, null=True)),
                ('ctps_serie', models.CharField(blank=True, help_text='Serie da CTPS', max_length=10, null=True)),
                ('ctps_uf', models.CharField(blank=True, help_text='UF de emissao da CTPS', max_length=2, null=True)),
                ('pis', models.CharField(blank=True, help_text='Numero do PIS/PASEP', max_length=20, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cargo', models.ForeignKey(help_text='Cargo do funcionario', on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='rh.cargo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa do grupo onde esta alocado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='comum.empresacnpj')),
                ('gestor', models.ForeignKey(blank=True, help_text='Gestor direto do funcionario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='rh.funcionario')),
                ('pessoa_fisica', models.OneToOneField(help_text='Dados pessoais do funcionario', on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to='comum.pessoafisica')),
                ('subcontrato', models.ForeignKey(blank=True, help_text='SubContrato para alocacao de custos', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='comum.subcontrato')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'funcionarios',
                'ordering': ['pessoa_fisica__nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, help_text='CPF do dependente (se possuir)', max_length=11, null=True)),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento', null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True)),
                ('parentesco', models.CharField(choices=[('conjuge', 'Conjuge'), ('companheiro', 'Companheiro(a)'), ('filho', 'Filho(a)'), ('enteado', 'Enteado(a)'), ('pai', 'Pai'), ('mae', 'Mae'), ('irmao', 'Irmao(a)'), ('avo', 'Avo(o)'), ('neto', 'Neto(a)'), ('tutelado', 'Menor Tutelado'), ('outro', 'Outro')], help_text='Grau de parentesco com o funcionario', max_length=20)),
                ('incluso_ir', models.BooleanField(default=False, help_text='Indica se e declarado no IR do funcionario')),
                ('incluso_plano_saude', models.BooleanField(default=False, help_text='Indica se esta incluso no plano de saude')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(help_text='Funcionario responsavel pelo dependente', on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Dependente',
                'verbose_name_plural': 'Dependentes',
                'db_table': 'dependentes',
                'ordering': ['funcionario', 'nome_completo'],
            },
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['nome'], name='cargos_nome_8b1d61_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['cbo'], name='cargos_cbo_be3cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['ativo'], name='cargos_ativo_7401be_idx'),
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['matricula'], name='funcionario_matricu_da2983_idx'),
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['status'], name='funcionario_status_ec7cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['departamento'], name='funcionario_departa_3fc0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['data_admissao'], name='funcionario_data_ad_476140_idx'),
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['subcontrato'], name='funcionario_subcont_045e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='dependente',
            index=models.Index(fields=['funcionario'], name='dependentes_funcion_b6ee48_idx'),
        ),
        migrations.AddIndex(
            model_name='dependente',
            index=models.Index(fields=['cpf'], name='dependentes_cpf_8d9a41_idx'),
        ),
        migrations.AddIndex(
            model_name='dependente',
            index=models.Index(fields=['parentesco'], name='dependentes_parente_7fee29_idx'),
        ),
    ]
